package com.kjipo.score



val DEFAULT_STEM_HEIGHT = 100
val DEFAULT_BAR_WIDTH = 1000

val DEFAULT_BEAM_HEIGHT = 12


val DEFAULT_VERTICAL_NOTE_SPACING = 12



val TICKS_PER_QUARTER_NOTE = 24

val START_NOTE_ELEMENT_MARGIN = 100

val EXTRA_BAR_LINE_LEFT_PADDING = 15
val EXTRA_BAR_LINE_RIGHT_PADDING = 15